import type { SVGProps } from 'react'
import {
  Home,
  Rss,
  BookOpen,
  MessageSquare,
  ListChecks,
  BarChart3,
  Layers,
  UserCheck,
  Bot,
  Shield,
  Search,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownRight,
  Sun,
  Moon,
  Command,
  Play,
  Pause,
  Mic,
  Image,
  Send,
  Sparkles,
  Zap,
  Flame,
  Target,
  Star,
  Bookmark,
  Clock,
  Calendar,
  Settings,
  User,
  Users,
  Upload,
  Download,
  Trash2,
  Pencil,
  Filter,
  ArrowUpDown,
  Code2,
  LayoutGrid,
  List,
  Bell,
  Eye,
  EyeOff,
  LogOut,
  Link2,
  Folder,
  Tag,
  Info,
  AlertTriangle,
  RefreshCw,
  Circle,
  Lock,
  Copy,
  Menu,
  type LucideIcon,
} from 'lucide-react'

// Maps this app's existing icon names (used via <Icon name="..." />) to lucide-react components.
const ICONS: Record<string, LucideIcon> = {
  home: Home,
  feed: Rss,
  book: BookOpen,
  chat: MessageSquare,
  quiz: ListChecks,
  progress: BarChart3,
  course: Layers,
  cards: Copy,
  interview: UserCheck,
  assistant: Bot,
  admin: Shield,
  search: Search,
  plus: Plus,
  chevR: ChevronRight,
  chevL: ChevronLeft,
  chevD: ChevronDown,
  chevU: ChevronUp,
  x: X,
  close: X,
  check: Check,
  arrow: ArrowRight,
  arrowL: ArrowLeft,
  'arrow-left': ArrowLeft,
  arrowUR: ArrowUpRight,
  arrowDR: ArrowDownRight,
  sun: Sun,
  moon: Moon,
  cmd: Command,
  play: Play,
  pause: Pause,
  mic: Mic,
  image: Image,
  send: Send,
  sparkle: Sparkles,
  bolt: Zap,
  zap: Zap,
  flame: Flame,
  target: Target,
  star: Star,
  bookmark: Bookmark,
  clock: Clock,
  calendar: Calendar,
  settings: Settings,
  user: User,
  users: Users,
  upload: Upload,
  download: Download,
  trash: Trash2,
  edit: Pencil,
  filter: Filter,
  sort: ArrowUpDown,
  layers: Layers,
  code: Code2,
  grid: LayoutGrid,
  list: List,
  bell: Bell,
  eye: Eye,
  'eye-off': EyeOff,
  logout: LogOut,
  link: Link2,
  folder: Folder,
  tag: Tag,
  info: Info,
  alert: AlertTriangle,
  refresh: RefreshCw,
  lock: Lock,
  dot: Circle,
  menu: Menu,
}

interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'ref'> {
  name: string
  size?: number
  strokeWidth?: number
}

export function Icon({ name, size = 16, strokeWidth = 1.5, className, ...props }: IconProps) {
  const LucideIcon = ICONS[name] ?? Circle
  return (
    <LucideIcon
      width={size}
      height={size}
      strokeWidth={strokeWidth}
      className={className}
      style={{ flexShrink: 0 }}
      {...props}
    />
  )
}
